require 'capybara/rspec'
require 'httparty'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.example_status_persistence_file_path = "spec/examples.txt"
  config.default_formatter = "doc" if config.files_to_run.one?
  config.include Capybara::DSL
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end



  config.order = 'random'

  config.before :suite do
    `kill $(lsof -ti tcp:4201)`
    npm = fork do
      exec 'npm start -- --port=4201'
    end
    Process.detach(npm)

    600.times do
      begin
        html = HTTParty.get 'http://localhost:4201'
        break if html.match /Welcome to app/
      rescue
        print '.'
        sleep 0.1
      end
    end
  end


  config.before(:each) do
  end

  config.after :suite do
    `kill $(lsof -ti tcp:4201)`
  end

  config.after :each do |example|
    if example.exception != nil
      save_page("saved_pages/capybara-#{Time.now.to_i}.html")
    end
  end

end

Capybara.configure do |config|
  config.run_server = false
  config.default_driver = :selenium_chrome
  config.javascript_driver = :selenium_chrome
  config.app_host = 'http://localhost:4201'
end
